# Generated by Django 5.2.8 on 2026-05-25 21:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_manage_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_calculo_icms',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Base de Cálculo ICMS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço'),
        ),
    ]
