# Generated by Django 5.2.8 on 2026-05-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_base_calculo_icms_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('sucos', 'Sucos'), ('cafes_premium', 'Cafés Premium'), ('cafes', 'Cafés'), ('salgados', 'Salgados'), ('minisalgados', 'Mini Salgados'), ('doces', 'Doces'), ('sanduiches', 'Sanduíches')], max_length=20, verbose_name='Categoria'),
        ),
    ]
