# Generated by Django 5.2.8 on 2026-05-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_pedidoitem_product_protect_and_name_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('salgados', 'Salgados'), ('cafes', 'Cafés'), ('cafes_premium', 'Cafés Premium'), ('minisalgados', 'Mini Salgados'), ('sanduiches', 'Sanduíches'), ('sucos', 'Sucos'), ('chas', 'Chás'), ('bebidas', 'Bebidas'), ('doces', 'Doces')], max_length=20, verbose_name='Categoria'),
        ),
    ]
