# Generated by Django 5.2.8 on 2026-05-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='opcional_obrigatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='products.opcionalobrigatorio', verbose_name='Sabor / Variação'),
        ),
        migrations.AddField(
            model_name='stockexit',
            name='opcional_obrigatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_exits', to='products.opcionalobrigatorio', verbose_name='Sabor / Variação'),
        ),
    ]
