# Generated by Django 5.2.8 on 2026-06-02 13:02

import core.storages
import utils.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_stockentry_opcional_obrigatorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.R2ImageStorage(), upload_to='combos/', validators=[utils.image_optimizer.validate_image_file_size], verbose_name='Imagem do Combo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.storages.R2ImageStorage(), upload_to='products/', validators=[utils.image_optimizer.validate_image_file_size], verbose_name='Imagem do Produto'),
        ),
    ]
