# Generated by Django 5.2.8 on 2026-06-11 22:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_combo_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aliq_cbs',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Alíquota CBS (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='aliq_ibs_mun',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Alíquota IBS Municipal (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='aliq_ibs_uf',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='Alíquota IBS Estadual (%)'),
        ),
    ]
