# Generated by Django 5.2.8 on 2026-06-15 20:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_ibs_cbs_aliquotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Custo médio por kg / L / un / pct', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Custo por Unidade (R$)'),
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='products.product', verbose_name='Produto')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to='products.rawmaterial', verbose_name='Matéria Prima')),
            ],
            options={
                'verbose_name': 'Ingrediente do Produto',
                'verbose_name_plural': 'Ingredientes do Produto',
                'ordering': ['raw_material__name'],
                'unique_together': {('product', 'raw_material')},
            },
        ),
    ]
