# Generated by Django 5.2.8 on 2026-06-02 13:02

import core.storages
import utils.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kioskslide',
            name='image',
            field=models.ImageField(storage=core.storages.R2ImageStorage(), upload_to='kiosk/slides/', validators=[utils.image_optimizer.validate_image_file_size], verbose_name='Imagem'),
        ),
    ]
