# Generated by Django 5.2.8 on 2026-01-26 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, verbose_name='Nome Fantasia')),
                ('inscricao_estadual', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(help_text='Formato: 00000-000', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('regime_tributario', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - Excesso de Sublimite'), ('3', 'Regime Normal')], default='1', max_length=1, verbose_name='Regime Tributário')),
                ('serie_nfce', models.PositiveIntegerField(default=1, help_text='Série padrão para emissão de NFCe', verbose_name='Série NFCe')),
                ('proximo_numero_nfce', models.PositiveIntegerField(default=1, help_text='Próximo número sequencial da NFCe', verbose_name='Próximo Número NFCe')),
                ('csc_id', models.PositiveIntegerField(help_text='ID do Token CSC cadastrado na SEFAZ', verbose_name='CSC ID')),
                ('csc_codigo', models.CharField(help_text='Código de Segurança do Contribuinte', max_length=36, verbose_name='Código CSC')),
                ('ambiente_nfce', models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação')], default='2', max_length=1, verbose_name='Ambiente NFCe')),
                ('ativa', models.BooleanField(default=True, verbose_name='Empresa Ativa')),
                ('cfop_padrao', models.CharField(default='5102', help_text='CFOP padrão para vendas (5102 - Venda no Estado)', max_length=4, verbose_name='CFOP Padrão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('arquivo_pfx', models.FileField(help_text='Arquivo do certificado digital A1', upload_to='certificados/', verbose_name='Arquivo Certificado (.pfx)')),
                ('senha_pfx', models.CharField(help_text='Senha para acessar o certificado .pfx', max_length=100, verbose_name='Senha do Certificado')),
                ('numero_serie', models.CharField(blank=True, max_length=50, verbose_name='Número de Série')),
                ('valido_ate', models.DateTimeField(help_text='Data de expiração do certificado', verbose_name='Válido até')),
                ('emissor', models.CharField(blank=True, max_length=200, verbose_name='Emissor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Certificado Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='companys.company')),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitais',
            },
        ),
    ]
