# Generated by Django 5.2.8 on 2026-02-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodigital',
            name='valido_ate',
            field=models.DateTimeField(blank=True, help_text='Data de expiração do certificado', null=True, verbose_name='Válido até'),
        ),
    ]
