# Generated by Django 5.2.8 on 2026-06-02 13:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_company_codigo_municipio_ibge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadodigital',
            name='arquivo_pfx',
            field=models.FileField(help_text='Arquivo do certificado digital A1', storage=django.core.files.storage.FileSystemStorage(), upload_to='certificados/', verbose_name='Arquivo Certificado (.pfx)'),
        ),
    ]
