# Generated by Django 5.2.8 on 2026-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nfce_chave',
            field=models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso NFCe'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfce_emitida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NFCe Emitida em'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfce_numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número NFCe'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfce_protocolo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Protocolo NFCe'),
        ),
    ]
