# Generated by Django 5.2.8 on 2026-04-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_order_remove_orderitem_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, help_text='Justificativa preenchida ao cancelar o pedido', null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
