# Generated by Django 5.2.8 on 2026-05-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_comanda_nfce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('em_uso', 'Em Uso'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='livre', max_length=20, verbose_name='Status'),
        ),
    ]
