# Generated by Django 5.2.8 on 2026-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_comanda_nfce_cancelamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('em_uso', 'Em Uso'), ('fechada', 'Fechada'), ('aguardando_caixa', 'Aguardando Caixa'), ('cancelada', 'Cancelada'), ('cortesia', 'Cortesia')], default='livre', max_length=20, verbose_name='Status'),
        ),
    ]
