# Generated by Django 5.2.8 on 2026-05-25 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_cancel_closed_comanda_permission'),
        ('products', '0020_pedidoitem_product_protect_and_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do Produto (snapshot)'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Produto'),
        ),
    ]
