# Generated by Django 5.2.8 on 2026-05-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_comandapartialpayment_created_by_and_more'),
        ('products', '0022_stockentry_opcional_obrigatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='opcional_obrigatorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_items', to='products.opcionalobrigatorio', verbose_name='Sabor / Variação'),
        ),
    ]
