# Generated by Django 5.2.8 on 2026-06-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_comanda_forma_pagamento_kiosk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Entregue'),
        ),
    ]
