# Generated by Django 5.2.8 on 2026-06-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dashboard_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dashboard_home',
            field=models.CharField(choices=[('home', 'Dashboard Principal (Comandas)'), ('ceo', 'Dashboard CEO'), ('manage', 'Dashboard Gerencial'), ('banks', 'Dashboard Gestão de Bancos')], default='home', help_text='Tela para a qual o usuário será redirecionado após o login.', max_length=20, verbose_name='Tela inicial'),
        ),
    ]
