# Generated by Django 5.2.8 on 2026-04-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='order',
        ),
    ]
