# Generated by Django 5.2.8 on 2026-04-14 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_remove_checkout_order'),
        ('orders', '0003_remove_orderitem_order_remove_orderitem_created_by_and_more'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM checkouts_checkout CASCADE;", "SELECT 1;"),
        migrations.AddField(
            model_name='checkout',
            name='comanda',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='orders.comanda', verbose_name='Comanda'),
            preserve_default=False,
        ),
    ]
