# Generated by Django 5.2.8 on 2026-05-02 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0004_sessaocaixa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('pix', 'PIX'), ('voucher', 'Voucher'), ('parcial', 'Pagamento Parcial'), ('cancelado', 'Cancelado')], default='dinheiro', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.CreateModel(
            name='CheckoutPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('payment_method', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão de Débito'), ('cartao_credito', 'Cartão de Crédito'), ('pix', 'PIX'), ('voucher', 'Voucher')], max_length=20, verbose_name='Forma de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='checkouts.checkout', verbose_name='Checkout')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['created_at'],
            },
        ),
    ]
