# Generated by Django 5.2.8 on 2026-04-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_order_time_minutes', models.PositiveIntegerField(default=20, help_text='Pedidos abertos após este tempo farão a comanda piscar em vermelho.', verbose_name='Tempo Máximo de Espera (minutos)')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
