# Generated by Django 5.2.8 on 2026-05-02 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_systemconfig_troco_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='quebra_negativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Margem máxima tolerada de falta em espécie (caixa com menos dinheiro do que o previsto).', max_digits=8, verbose_name='Quebra de Caixa Negativa (R$)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='quebra_positiva',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Margem máxima tolerada de sobra em espécie (caixa com mais dinheiro do que o previsto).', max_digits=8, verbose_name='Quebra de Caixa Positiva (R$)'),
        ),
    ]
