# Generated by Django 5.2.8 on 2026-05-19 13:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_split_config_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'Configuração do Sistema (legado)', 'verbose_name_plural': 'Configurações do Sistema (legado)'},
        ),
        migrations.AlterField(
            model_name='configcomissao',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual de comissão pago ao operador sobre o total de vendas do período.', max_digits=5, verbose_name='Comissão sobre Vendas (%)'),
        ),
        migrations.AlterField(
            model_name='configquebracaixa',
            name='quebra_negativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Margem máxima tolerada de falta em espécie.', max_digits=8, verbose_name='Quebra de Caixa Negativa (R$)'),
        ),
        migrations.AlterField(
            model_name='configquebracaixa',
            name='quebra_positiva',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Margem máxima tolerada de sobra em espécie.', max_digits=8, verbose_name='Quebra de Caixa Positiva (R$)'),
        ),
        migrations.AlterField(
            model_name='configtempoespera',
            name='max_order_time_minutes',
            field=models.PositiveIntegerField(default=20, help_text='Pedidos abertos após este tempo farão a comanda piscar em vermelho.', verbose_name='Tempo Máximo de Espera (minutos)'),
        ),
        migrations.AlterField(
            model_name='configtrocoinicial',
            name='troco_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Valor padrão com que o caixa inicia todos os dias.', max_digits=8, verbose_name='Troco Inicial (R$)'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='max_order_time_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='quebra_negativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='quebra_positiva',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='troco_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=8),
        ),
    ]
