# Generated by Django 5.2.8 on 2026-05-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_add_synclog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
