# Generated by Django 5.2.8 on 2026-01-09 15:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinpad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Ex: Stone Terminal 1, Cielo Caixa Principal', max_length=100, verbose_name='Nome do Pinpad')),
                ('description', models.TextField(blank=True, help_text='Descrição adicional do pinpad', verbose_name='Descrição')),
                ('provider', models.CharField(choices=[('stone', 'Stone'), ('cielo', 'Cielo'), ('rede', 'Rede'), ('pagseguro', 'PagSeguro'), ('mercado_pago', 'Mercado Pago'), ('getnet', 'Getnet'), ('safrapay', 'Safrapay'), ('bin', 'Bin'), ('outros', 'Outros')], help_text='Operadora da maquininha', max_length=20, verbose_name='Provedor')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção'), ('teste', 'Teste')], default='inativo', max_length=20, verbose_name='Status')),
                ('api_url', models.URLField(help_text='URL base da API do provedor', validators=[django.core.validators.URLValidator()], verbose_name='URL da API')),
                ('api_key', models.CharField(help_text='Chave de acesso da API', max_length=500, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, help_text='Chave secreta da API (se necessário)', max_length=500, verbose_name='API Secret')),
                ('merchant_id', models.CharField(blank=True, help_text='Identificação do estabelecimento', max_length=100, verbose_name='ID do Merchant')),
                ('terminal_id', models.CharField(blank=True, help_text='Identificação do terminal/pinpad', max_length=100, verbose_name='ID do Terminal')),
                ('supports_credit', models.BooleanField(default=True, help_text='Pinpad aceita pagamentos no crédito', verbose_name='Suporta Crédito')),
                ('supports_debit', models.BooleanField(default=True, help_text='Pinpad aceita pagamentos no débito', verbose_name='Suporta Débito')),
                ('supports_contactless', models.BooleanField(default=False, help_text='Pinpad aceita pagamentos por aproximação', verbose_name='Suporta Contactless')),
                ('credit_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa percentual do crédito (Ex: 2.49 para 2,49%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Taxa Crédito (%)')),
                ('debit_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa percentual do débito (Ex: 1.99 para 1,99%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Taxa Débito (%)')),
                ('credit_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa fixa por transação de crédito em reais', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Taxa Fixa Crédito (R$)')),
                ('debit_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa fixa por transação de débito em reais', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Taxa Fixa Débito (R$)')),
                ('timeout', models.IntegerField(default=60, help_text='Tempo limite para transações', verbose_name='Timeout (segundos)')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo permitido para transações', max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('is_default', models.BooleanField(default=False, help_text='Usar como pinpad padrão do sistema', verbose_name='Pinpad Padrão')),
                ('is_active', models.BooleanField(default=True, help_text='Pinpad ativo no sistema', verbose_name='Ativo')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Data do último teste de conexão', null=True, verbose_name='Último Teste')),
                ('last_test_success', models.BooleanField(default=False, help_text='Resultado do último teste', verbose_name='Último Teste Sucesso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pinpads_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pinpads_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Pinpad',
                'verbose_name_plural': 'Pinpads',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
    ]
