# Generated by Django 5.2.8 on 2026-01-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinpad',
            name='pix_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa percentual do PIX', max_digits=5, verbose_name='Taxa PIX (%)'),
        ),
        migrations.AddField(
            model_name='pinpad',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Chave PIX para recebimentos', max_length=200, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='pinpad',
            name='supports_pix',
            field=models.BooleanField(default=False, help_text='Pinpad aceita pagamentos via PIX', verbose_name='Suporta PIX'),
        ),
        migrations.AddField(
            model_name='pinpad',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL para receber notificações', verbose_name='Webhook URL'),
        ),
    ]
