# Generated by Django 5.2.8 on 2026-06-09 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinpads', '0002_pinpad_pix_fee_percentage_pinpad_pix_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinpad',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Pinpad', 'verbose_name_plural': 'Pinpads'},
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='credit_fee_fixed',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='credit_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='debit_fee_fixed',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='debit_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='last_test_at',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='last_test_success',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='max_amount',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='pix_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='pix_key',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='supports_contactless',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='supports_credit',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='supports_debit',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='supports_pix',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='terminal_id',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='timeout',
        ),
        migrations.RemoveField(
            model_name='pinpad',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='pinpad',
            name='dias_credito',
            field=models.PositiveIntegerField(default=30, verbose_name='Dias Crédito'),
        ),
        migrations.AddField(
            model_name='pinpad',
            name='dias_debito',
            field=models.PositiveIntegerField(default=1, verbose_name='Dias Débito'),
        ),
        migrations.AddField(
            model_name='pinpad',
            name='dias_pix',
            field=models.PositiveIntegerField(default=1, verbose_name='Dias PIX'),
        ),
        migrations.AlterField(
            model_name='pinpad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='pinpad',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Pinpad'),
        ),
        migrations.CreateModel(
            name='BandeiraPinpad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Bandeira')),
                ('taxa_credito', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa Crédito (%)')),
                ('taxa_debito', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa Débito (%)')),
                ('pinpad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandeiras', to='pinpads.pinpad')),
            ],
            options={
                'verbose_name': 'Bandeira',
                'verbose_name_plural': 'Bandeiras',
                'ordering': ['nome'],
            },
        ),
    ]
