# Generated by Django 5.2.8 on 2026-06-07 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('numero_conta', models.CharField(blank=True, max_length=50, verbose_name='Número da Conta')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('valor_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Inicial')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nome'],
            },
        ),
    ]
