# Generated by Django 5.2.8 on 2026-06-10 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_add_bank_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False, verbose_name='Visualizar')),
                ('can_change', models.BooleanField(default=False, verbose_name='Editar')),
                ('can_add_transaction', models.BooleanField(default=False, verbose_name='Lançar transações')),
                ('can_delete_transaction', models.BooleanField(default=False, verbose_name='Remover transações')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='banks.bank', verbose_name='Banco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acesso ao Banco',
                'verbose_name_plural': 'Acessos a Bancos',
                'unique_together': {('user', 'bank')},
            },
        ),
    ]
