# Generated by Django 5.2.8 on 2026-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_split_bank_transaction_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccess',
            name='can_add_transaction',
            field=models.BooleanField(default=False, verbose_name='Adicionar depósito'),
        ),
    ]
