# Generated by Django 5.2.8 on 2026-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_userbankaccess_can_add_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='bank_comprovantes/', verbose_name='Comprovante'),
        ),
    ]
