# Generated by Django 5.2.8 on 2026-06-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_banktransaction_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='bandeira',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bandeira'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='metodo_pagamento',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Método'),
        ),
    ]
