# Generated by Django 5.2.8 on 2026-06-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_add_metodo_bandeira_to_banktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='bank_comprovantes/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='banks.banktransaction')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
