# Generated by Django 5.2.8 on 2026-01-15 22:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor em reais que foi retirado do caixa', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Sangria')),
                ('observacao', models.TextField(blank=True, help_text='Motivo ou observação sobre a sangria', null=True, verbose_name='Observação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('usuario', models.ForeignKey(help_text='Usuário que realizou a sangria', on_delete=django.db.models.deletion.CASCADE, related_name='sangrias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Sangria',
                'verbose_name_plural': 'Sangrias',
                'ordering': ['-created_at'],
                'permissions': [('can_view_sangria', 'Can view sangria'), ('can_add_sangria', 'Can add sangria')],
            },
        ),
    ]
