# Generated by Django 5.2.8 on 2026-05-02 22:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoCaixaDiario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data', models.DateField(unique=True, verbose_name='Data do Fechamento')),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Troco Inicial')),
                ('total_dinheiro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Dinheiro')),
                ('total_debito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cartao Debito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cartao Credito')),
                ('total_pix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='PIX')),
                ('total_voucher', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Voucher')),
                ('total_sangrias', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sangrias')),
                ('total_entradas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Entradas')),
                ('total_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Final em Caixa')),
                ('total_comandas', models.PositiveIntegerField(default=0, verbose_name='Qtd Comandas')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fechado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_caixa', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Fechamento de Caixa Diario',
                'verbose_name_plural': 'Fechamentos de Caixa Diarios',
                'ordering': ['-data'],
            },
        ),
    ]
