# Generated by Django 5.2.8 on 2026-05-21 01:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_caixaadm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaMalote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='despesas_malote/', verbose_name='Comprovante')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('malote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='financials.caixaadm', verbose_name='Malote')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_malote', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Despesa do Malote',
                'verbose_name_plural': 'Despesas do Malote',
                'ordering': ['-registrado_em'],
            },
        ),
    ]
