# Generated by Django 5.2.8 on 2026-05-21 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_despesamalote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaadm',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AddField(
            model_name='caixaadm',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Concluído em'),
        ),
        migrations.AddField(
            model_name='caixaadm',
            name='concluido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malotes_concluidos', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por'),
        ),
    ]
