# Generated by Django 5.2.8 on 2026-06-07 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_caixaadm_concluido_caixaadm_concluido_em_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamentocaixadiario',
            options={'ordering': ['-data'], 'permissions': [('view_financial', 'Pode visualizar relatórios financeiros (extrato e fechamento)')], 'verbose_name': 'Fechamento de Caixa Diario', 'verbose_name_plural': 'Fechamentos de Caixa Diarios'},
        ),
    ]
