# Generated by Django 5.2.8 on 2026-06-07 21:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_add_bank_transaction'),
        ('financials', '0006_add_view_financial_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaAdmTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('banco_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_caixa_adm', to='banks.bank', verbose_name='Banco destino')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_caixa_adm', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Transferência Caixa ADM',
                'verbose_name_plural': 'Transferências Caixa ADM',
                'ordering': ['-criado_em'],
            },
        ),
    ]
