# Generated by Django 5.2.8 on 2026-06-09 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_add_caixaadm_transferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteFechamentoCaixaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ajustado_em', models.DateTimeField(auto_now_add=True, verbose_name='Ajustado em')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Troco Inicial')),
                ('total_dinheiro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinheiro')),
                ('total_debito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Débito')),
                ('total_credito', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Crédito')),
                ('total_pix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PIX')),
                ('total_sangrias', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sangrias')),
                ('total_entradas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Entradas')),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Final')),
                ('observacao', models.TextField(blank=True, verbose_name='Motivo do ajuste')),
                ('ajustado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_fechamento', to=settings.AUTH_USER_MODEL, verbose_name='Ajustado por')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='financials.fechamentocaixadiario', verbose_name='Fechamento')),
            ],
            options={
                'verbose_name': 'Ajuste de Fechamento',
                'verbose_name_plural': 'Ajustes de Fechamento',
                'ordering': ['-ajustado_em'],
            },
        ),
    ]
