# Generated by Django 5.2.8 on 2026-06-09 01:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_ajuste_fechamento_caixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_total_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Crédito (antes)'),
        ),
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_total_debito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Débito (antes)'),
        ),
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_total_dinheiro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Dinheiro (antes)'),
        ),
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_total_final',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Final (antes)'),
        ),
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_total_pix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='PIX (antes)'),
        ),
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_total_sangrias',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Sangrias (antes)'),
        ),
        migrations.AddField(
            model_name='ajustefechamentocaixadiario',
            name='prev_valor_inicial',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Troco Inicial (antes)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_credito',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Crédito (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_debito',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Débito (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_dinheiro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dinheiro (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_entradas',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Entradas (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_final',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Final (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_pix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PIX (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='total_sangrias',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sangrias (depois)'),
        ),
        migrations.AlterField(
            model_name='ajustefechamentocaixadiario',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Troco Inicial (depois)'),
        ),
    ]
