# Generated by Django 5.2.8 on 2026-06-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0009_ajuste_com_valores_anteriores'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaadmtransferencia',
            name='bandeira',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bandeira'),
        ),
        migrations.AddField(
            model_name='caixaadmtransferencia',
            name='data_caixa',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Caixa'),
        ),
        migrations.AddField(
            model_name='caixaadmtransferencia',
            name='metodo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Débito'), ('credito', 'Crédito'), ('pix', 'PIX')], default='dinheiro', max_length=10, verbose_name='Método'),
        ),
    ]
