# Generated by Django 5.2.8 on 2026-06-17 23:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0014_add_cancelada_fechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaadmtransferencia',
            name='taxa_aplicada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taxa aplicada (%)'),
        ),
    ]
