# Generated by Django 5.2.8 on 2026-06-23 22:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0015_add_taxa_aplicada_caixaadmtransferencia'),
        ('products', '0025_rawmaterial_unit_cost_productingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome / Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='financials.planodecontas', verbose_name='Conta Pai')),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FornecedorProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='financials.fornecedor', verbose_name='Fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='products.product', verbose_name='Produto')),
                ('plano_de_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor_produtos', to='financials.planodecontas', verbose_name='Plano de Contas')),
            ],
            options={
                'verbose_name': 'Produto do Fornecedor',
                'verbose_name_plural': 'Produtos do Fornecedor',
                'unique_together': {('fornecedor', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('data_vencimento', models.DateField(verbose_name='Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('pago_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_pagas', to=settings.AUTH_USER_MODEL, verbose_name='Pago por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='financials.fornecedor', verbose_name='Fornecedor')),
                ('fornecedor_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='financials.fornecedorproduto', verbose_name='Produto')),
                ('plano_de_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='financials.planodecontas', verbose_name='Plano de Contas')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
