# Generated by Django 5.2.8 on 2026-06-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0016_contas_pagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planodecontas',
            options={'ordering': ['nome'], 'verbose_name': 'Plano de Contas', 'verbose_name_plural': 'Plano de Contas'},
        ),
        migrations.RemoveField(
            model_name='planodecontas',
            name='codigo',
        ),
    ]
