# Generated by Django 5.2.8 on 2026-06-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0017_remove_codigo_plano_de_contas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planodecontas',
            name='pai',
        ),
    ]
