# Generated by Django 5.2.8 on 2026-06-24 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0018_remove_pai_plano_de_contas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='contapagar',
            name='fornecedor_produto',
        ),
        migrations.CreateModel(
            name='FornecedorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='financials.fornecedor', verbose_name='Fornecedor')),
                ('plano_de_conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedor_materiais', to='financials.planodecontas', verbose_name='Plano de Contas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='financials.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material do Fornecedor',
                'verbose_name_plural': 'Materiais do Fornecedor',
                'unique_together': {('fornecedor', 'material')},
            },
        ),
        migrations.AddField(
            model_name='contapagar',
            name='fornecedor_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to='financials.fornecedormaterial', verbose_name='Material'),
        ),
        migrations.DeleteModel(
            name='FornecedorProduto',
        ),
    ]
