# Generated by Django 5.2.8 on 2026-06-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0020_conta_pagar_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('unidade_medida', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Kg'), ('g', 'Gramas'), ('l', 'Litros'), ('ml', 'ml'), ('cx', 'Caixa'), ('pc', 'Pacote'), ('fd', 'Fardo'), ('sc', 'Saco'), ('lt', 'Lata'), ('dz', 'Dúzia'), ('m', 'Metro')], default='un', max_length=5, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='financials.contapagar', verbose_name='Conta')),
                ('fornecedor_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_conta_pagar', to='financials.fornecedormaterial', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Item de Conta a Pagar',
                'verbose_name_plural': 'Itens de Conta a Pagar',
                'ordering': ['pk'],
            },
        ),
    ]
