# Generated by Django 5.2.8 on 2026-06-24 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_add_taxa_tx_to_banktransaction'),
        ('financials', '0021_conta_pagar_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='banco_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagas', to='banks.bank', verbose_name='Banco do pagamento'),
        ),
    ]
