# Generated by Django 5.2.8 on 2026-07-01 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_add_taxa_tx_to_banktransaction'),
        ('financials', '0022_banco_pagamento_conta_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaadmtransferencia',
            name='bank_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixa_transferencia', to='banks.banktransaction', verbose_name='BankTransaction vinculada'),
        ),
    ]
